version: '3'
services:
  db:
    image: postgres:11
    expose:
      - "5432"
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postrgesql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: FASTAPI